### ISSUE TITLE
Use standard names for languages

### ISSUE THREAD

**Issue by guntbert** [briandfoy/perl6-chemistry-elements#16]
When we are distinguishing between "generic English" and "british English" it might be useful to adopt the languagecode_Countrycode schema (al least additionally)

- en: remains the generic name
- en_UK: for british (instead of the proposed "brit")

So as long as there is only one form of a language (like "de") at the moment, the single two character symbol is fine.

**Comment by mridulg** [comment]
@guntbert will work on it.

**Comment by guntbert** [comment]
@mridulg wait a moment - I have no authority here (just came in :smile ) - you might want to hear what one of the regulars says.

**Comment by briandfoy** [comment]
Done.
