### ISSUE TITLE
Languages should be defined in a "central" place

### ISSUE THREAD

**Issue by guntbert** [briandfoy/perl6-chemistry-elements#17]
With a new language several files must be adapted (the one with the words(Elements.pm6 as of now)/the one to import words) and all tests.
So I suggest to create some kind of file with all the languages and their symbols.

**Comment by mridulg** [comment]
@guntbert, so files with name `<language>.txt` or `<language>.pm6` need to be created to be read from, right?

**Comment by guntbert** [comment]
@mridulg Sorry, I really cannot say - it was just an observation from a bystander.

**Comment by briandfoy** [comment]
You actually mean the opposite of central (which is the current situation). But, this is also #13 so I'm closing this as a duplicate.

**Comment by guntbert** [comment]
@briandfoy you misunderstood: I suggest one file for matching language names with their "symbols", i.e.

>English - en
>British English - en_UK
>French - fr

**Comment by briandfoy** [comment]
Ah, I see. I was thinking that each language file would have a header identifying what it represents. That way we just drop in a single file to add a new language.

**Comment by guntbert** [comment]
I see - that makes my idea obsolete, reduces workload for maintaining.

**Comment by briandfoy** [comment]
keep the ideas coming though. :)
