### ISSUE TITLE
Use IUPAC symbols for the newly named heavy elements

### ISSUE THREAD

**Issue by bruceravel** [briandfoy/perl6-chemistry-elements#29]
You have the symbols `Uut`, `Uup`, 'Uus`, and `Uuo` at https://github.com/briandfoy/perl6-chemistry-elements/blob/master/lib/Chemistry/Elements.pm6#L217 while you have the new IUPAC names for those elements at https://github.com/briandfoy/perl6-chemistry-elements/blob/master/lib/Chemistry/Elements.pm6#L173-L180

The same is true in the perl5 version (1.071) of this module.

**Comment by briandfoy** [comment]
Done. Thanks. ca34d42c157de06566adcf01605eb9ef005f860c
