### ISSUE TITLE
Add another language, and a way to switch to it

### ISSUE THREAD

**Issue by briandfoy** [briandfoy/perl6-chemistry-elements#3]
Perhaps German?

Have a way to set the default language, and maybe have a default argument for some of the methods that return the names.

**Comment by B1T0** [comment]
I added a German translation and an argument for the methods that return names in #9. Nevertheless this doesn't set a default language..

**Comment by briandfoy** [comment]
This is a really good start! Thanks!

The next step is to switch languages by name, like 'en' or 'de' or something instead of the number in the array. And, I'll have to look closer to see how to deal with default languages. Should that look at the locale or will that be too weird?

**Comment by B1T0** [comment]
I think looking at the locale is a very good idea. Then we could change the language by giving an alternative locale string.

**Comment by B1T0** [comment]
In #10 I changed the way of choosing the language. Since I don't know how to read the locale I set the default language to English.

**Comment by briandfoy** [comment]
I'm closing this issue and we can have finer grained issues for enhancements.
